### ISSUE TITLE
신규 놀이 기능

### ISSUE THREAD

**Issue by Whitetiger0423** [dev-White-team/WhiteBot#22]
# 설명
WhiteBot이 유틸리티 봇인만큼, 어느정도의 놀이 기능도 있으면 좋겠다는 생각에 신규 놀이기능 몇가지를 추가시키려 합니다.

## 기능 목록

- [x] `feature/holjjac` - 홀짝 기능 추가 (by @YonginStudent)
- [x] `feature/tictactoe` - 틱택토(삼목) 기능 추가 (by @Whitetiger0423)
- [ ] dev-White-team/PastelBot#1
- [ ] dev-White-team/PastelBot#2

## 추가 사항
`Wordle` 기능은 한명으로는 끝나지 않을 것 같아, @dev-White-team/whitebot-developer 팀의 두명 이상이 협업할 예정입니다.

**Comment by nkgcp** [comment]
마일스톤에 넣기 위해 `wordle`과 `2048`을 별도의 이슈로 분리합니다.

**Comment by Whitetiger0423** [comment]
`wordle`과 `2048` 이슈를 타 프로젝트로 옮기며 이슈를 종료합니다.
