### ISSUE TITLE
계산 기능

### ISSUE THREAD

**Issue by froggal** [dev-White-team/WhiteBot#40]
우리 흰색봇은 '유틸리티' 봇입니다. 유틸리티이니 유틸리티 봇 답게 계산 기능이 있으면 좋을 것 같습니다. 파이선에서 계산은 간단하게 할 수 있으니, 일단 제가 할 수 있는대로 구현하겠습니다.

**Comment by froggal** [comment]
살리셨네요.
뭐 제가 간단하게 구현을 했습니다. 브랜치 바꿔보시면 알아요~

**Comment by froggal** [comment]
이런 방식을 첨 해봐서.. 잘못된거 있다면 수정 부탁드려요 !!

**Comment by froggal** [comment]
**현재 체크 표시(code.py에도 있는 완료시 체크 표시)가 나타나지 않습니다.** 그 부분은 임시로 삭제하였고, 해결책 아시는 분은 한 번 수정 부탁드립니다.

**Comment by Whitetiger0423** [comment]
@froggal 이모지가 있는 서버에 봇이 속해있어야 이모지가 작동합니다. 베타봇 토큰 이용하셔서 다시 테스트해보세요.

**Comment by froggal** [comment]
@Whitetiger0423 맥에서 애러가 납니다. 나중이 한 번 디코로 보내드릴깨요.

**Comment by nkgcp** [comment]
근데 다수의 서버에서 사용되는 화이트봇이라면
하나의 서버에서만 작동하는 내용을 넣어두면 안되지 않을까요?

**Comment by Whitetiger0423** [comment]
하나의 서버에서만 작동하는게 아니라, 봇이 커스텀 이모지를 사용하기 위해서는 그 커스텀 이모지가 있는 서버에 들어와있어야 된다는 뜻입니다. 현재 키페님의 봇은 저희 팀 서버에 들어와있지 않으니 이모지를 사용할 수 없지만, WhiteBot은 팀 서버에.들어와있으니 어느 서버에서나 저희 팀 서버의 커스텀 이모지 사용이 가능합니다.

**Comment by froggal** [comment]
오 감사합니다 ㅎㅎ
