### ISSUE TITLE
주석 처리

### ISSUE THREAD

**Issue by froggal** [dev-White-team/WhiteBot#56]
주석은, 프로그램에서 `~~ 작업 수행` 과 같이 코드를 더 이해하기 쉽게 넣는 메모입니다. 하지만 WhiteBot에는 라이선스 표기밖에 없습니다. 이에 따라, 제가 주석을 추가할 예정입니다. 작업은 `feature/memo` 브랜치에서 작업할 예정이고, 소스 코드를 새로 만들지 않고 원본 코드에 주석만 추가하는 작업입니다. 감사합니다.

**Comment by froggal** [comment]
?? 깃허브 웹에서 Branch > All Branch 눌러도 브랜치 생성 버튼 안 보이고 PR도 생성이 안 되는데요?

**Comment by Whitetiger0423** [comment]
외부 기여자는 레포지토리를 클론하여 브런치를 만든 후 작업하여야 합니다. [기여 가이드](https://github.com/dev-White-team/WhiteBot/blob/3543a6d064a5a336330bb45531bdff06c0f68407/CONTRIBUTING.md)를 참고해주세요.

**Comment by froggal** [comment]
아 포크해야하군요. 알겠습니다.

**Comment by froggal** [comment]
https://github.com/froggal/WhiteBot 처럼 하면 되나요?

**Comment by Whitetiger0423** [comment]
> 도움이 필요하시다면 [Team White 디스코드](https://discord.gg/aebSVBgzuG)에서 도와드리겠습니다.

기여를 하실때엔 반드시 기여 가이드를 읽으신 뒤 기여해주시기 바랍니다.

**Comment by froggal** [comment]
알겠습니다.

**Comment by Whitetiger0423** [comment]
한달 가량이 지났지만 작업이 이루어지지 않는것으로 판단하고 이슈를 닫습니다.
