### ISSUE TITLE
환율 정보

### ISSUE THREAD

**Issue by Whitetiger0423** [dev-White-team/WhiteBot#61]
## 필수
- [x] 한국 원화(KRW) -> 미국 달러(USD)
- [x] 미국 달러(USD) -> 한국 원화(KRW)
## 선택
- [x] 한국 원화(KRW) -> 일본 엔화(JPY)
- [x] 일본 엔화(JPY) -> 한국 원화(KRW)
- [x] 그 외 통화(유럽 유로, 중국 위안, 러시아 루블...)

**Comment by 9Hundred100Five1** [comment]
현재 작성중인 api에서는 한국 원화 -> 22개국 통화 밖에 지원이 안되는데,  이 부분은 매 정기 업데이트 시 마다 개선해 나가는 방향으로 해도 될까요?

**Comment by Whitetiger0423** [comment]
가능합니다 :)

**Comment by 9Hundred100Five1** [comment]
확인했습니다!

**Comment by star0202** [comment]
#68 완료되었습니다
